name: Update Documentation
on:
  workflow_dispatch:
    inputs:
      dictionary_link:
        description: "Link to the dictionary stored on OSF"
        required: true
        default: 'missing'
      past_dictionary_link:
        description: "Link to the previous dictionary stored on OSF"
        required: true
        default: 'missing'
      osf_token:
        description: "Personal OSF token to use for the download"
        required: true
        default: 'missing'
jobs:
  build-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: R-package
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: setup-r
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.1.1"
      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-direcotyr: R-package
      - name: Run dictionary validation and file creation
        run: R -e 'PHES.ODM::create_release_files(OSF_LINK_RELEASE = ${{github.event.inputs.dictionary_link}}, OSF_LINK_PAST_RELEASE = ${{github.event.inputs.dictionary_link}}, OSF_TOKEN = ${{github.event.inputs.osf_token}}, dictionary_path = "data/raw", past_dictionary_path = "data/raw")'